### ISSUE TITLE
smtp localhost port 25 hardcoded in post-build publisher

### ISSUE THREAD

**Issue by ghost** [DotCi/jenkinsci-dotci-example#1]
build will always fail for now till https://github.com/groupon/DotCi/issues/169 is resolved unless smtp setup exits on localhost ... 

since docker does not support multi-inheritance, it would be ideal to avoid having to modify the jenkinsci Dockerfile to also include https://hub.docker.com/r/catatnight/postfix.

**Comment by ghost** [comment]
Code is not respecting [Jenkins.instance.getDescriptor("hudson.tasks.Mailer").setSmtpHost("mailman")](https://github.com/DotCi/jenkinsci-dotci-example/blob/master/configure-dotci.groovy#L39)

I'm now working to fix https://github.com/groupon/DotCi/blob/master/src/main/java/com/groupon/jenkins/notifications/EmailNotifierBase.java to instead use [Transport.send(Message msg, Address[] addresses)](https://docs.oracle.com/javaee/6/api/javax/mail/Transport.html#send%28javax.mail.Message,%20javax.mail.Address[]%29)

**Comment by ghost** [comment]
84b30ff1dc0ac888dc3967b5e16baa063531bef1

```
mailman:
  image: catatnight/postfix
  environment:
    maildomain: "mail.example.com"
    smtp_user: "user:password"
  ports:
    - "25:25"
```
